modLoader="neoForge"
loaderVersion="[21,22)"

[[mods]]
modId="chattabs-reloaded"
version="${mod_version}"
displayName="ChatTabs Reloaded"
description='''Adds customizable, user-configurable chat tabs and filters — ChatTabs Reloaded (fork by Wakcedon)'''
authors = ["Wakcedon", "Gri11edHam"]
