modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "chattabs_reloaded"
version = "${mod_version}"
displayName = "ChatTabs Reloaded"
logoFile = "chattabs_reloaded/icon.png"
credits = "Wakcedon, Gri11edHam"
authors = "Wakcedon"
side = "CLIENT"
description = '''
Adds customizable, user-configurable chat tabs and filters — ChatTabs Reloaded (fork by Wakcedon)
'''
displayURL = "https://modrinth.com/mod/chattabs-reloaded"
issueTrackerURL = "https://github.com/Wakcedon/ChatTabs/issues"

[[mixins]]
config = "chattabs_reloaded.mixins.json"

[[dependencies.chattabs_reloaded]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.22)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.chattabs_reloaded]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21,)"
    ordering = "NONE"
    side = "CLIENT"
